# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\tinventory\"5\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\"\x1c\n\x0eProductRequest\x12\n\n\x02id\x18\x01 \x01(\t\"7\n\x12StockUpdateRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\r\n\x05\x64\x65lta\x18\x02 \x01(\x05\"!\n\x0c\x41lertRequest\x12\x11\n\tthreshold\x18\x01 \x01(\x05\"P\n\nStockAlert\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x14\n\x0cproduct_name\x18\x02 \x01(\t\x12\x18\n\x10\x63urrent_quantity\x18\x03 \x01(\x05\".\n\x0fProductResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\"!\n\x0eRemoveResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"<\n\x14ListProductsResponse\x12$\n\x08products\x18\x01 \x03(\x0b\x32\x12.inventory.Product\"\x07\n\x05\x45mpty2\xac\x03\n\x10InventoryService\x12>\n\nAddProduct\x12\x12.inventory.Product\x1a\x1a.inventory.ProductResponse\"\x00\x12=\n\nGetProduct\x12\x19.inventory.ProductRequest\x1a\x12.inventory.Product\"\x00\x12\x42\n\x0bUpdateStock\x12\x1d.inventory.StockUpdateRequest\x1a\x12.inventory.Product\"\x00\x12G\n\rRemoveProduct\x12\x19.inventory.ProductRequest\x1a\x19.inventory.RemoveResponse\"\x00\x12\x43\n\x0cListProducts\x12\x10.inventory.Empty\x1a\x1f.inventory.ListProductsResponse\"\x00\x12G\n\x11StreamStockAlerts\x12\x17.inventory.AlertRequest\x1a\x15.inventory.StockAlert\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCT']._serialized_start=30
  _globals['_PRODUCT']._serialized_end=83
  _globals['_PRODUCTREQUEST']._serialized_start=85
  _globals['_PRODUCTREQUEST']._serialized_end=113
  _globals['_STOCKUPDATEREQUEST']._serialized_start=115
  _globals['_STOCKUPDATEREQUEST']._serialized_end=170
  _globals['_ALERTREQUEST']._serialized_start=172
  _globals['_ALERTREQUEST']._serialized_end=205
  _globals['_STOCKALERT']._serialized_start=207
  _globals['_STOCKALERT']._serialized_end=287
  _globals['_PRODUCTRESPONSE']._serialized_start=289
  _globals['_PRODUCTRESPONSE']._serialized_end=335
  _globals['_REMOVERESPONSE']._serialized_start=337
  _globals['_REMOVERESPONSE']._serialized_end=370
  _globals['_LISTPRODUCTSRESPONSE']._serialized_start=372
  _globals['_LISTPRODUCTSRESPONSE']._serialized_end=432
  _globals['_EMPTY']._serialized_start=434
  _globals['_EMPTY']._serialized_end=441
  _globals['_INVENTORYSERVICE']._serialized_start=444
  _globals['_INVENTORYSERVICE']._serialized_end=872
# @@protoc_insertion_point(module_scope)
